HackathonTeamBuilder/Models/Hackathon.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HackathonTeamBuilder.Models
{
    public class Hackathon
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(255, ErrorMessage = "Name must be at most 255 characters.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Location is required.")]
        [StringLength(255, ErrorMessage = "Location must be at most 255 characters.")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(300, ErrorMessage = "Description must be at most 300 characters.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "URL is required.")]
        [StringLength(255, ErrorMessage = "URL must be at most 255 characters.")]
        public string Url { get; set; }

        [Required(ErrorMessage = "Deadline is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid deadline format.")]
        public DateTime Deadline { get; set; }

    }
}

HackathonTeamBuilder/Models/HackathonsViewModel.cs
using System.Collections.Generic;

namespace HackathonTeamBuilder.Models
{
    public class HackathonsViewModel
    {
        public List<Hackathon> Hackathons { get; set; }
        public ApplicationUser CurrentUser { get; set; }
    }
}

HackathonTeamBuilder/Controllers/HackathonController.cs
using HackathonTeamBuilder.Models;
using System.Diagnostics;
using System.Net.Http;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HackathonTeamBuilder.Controllers
{
    public class HackathonController : Controller
    {
        private readonly HttpClient client;
        private readonly JavaScriptSerializer jss;
        public HackathonController()
        {
            client = new HttpClient();
            client.BaseAddress = new System.Uri(Constant.BASE_URL);
            jss = new JavaScriptSerializer();
        }
        // GET: Hackathon/Detail
        public ActionResult Detail()
        {

            return View();
        }

        // GET: Hackathon/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // Post: Hackathon/Create
        [HttpPost]
        public ActionResult Create(Hackathon hackathon)
        {
            string url = "hackathondata/create";
            string jsonpayload = jss.Serialize(hackathon);
            Debug.WriteLine(jsonpayload);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // return to error action and give the error message
                return RedirectToAction("Error", new { message = "Unable to create the hackathon" });
            }
        }

        /// <summary>
        /// Render Edit form for hackathon
        /// </summary>
        /// <param name="id">hackathon id</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            //the existing hackathon information
            string endpoint = "hackathondata/findbyid/" + id;
            HttpResponseMessage response = client.GetAsync(endpoint).Result;
            Hackathon selectedHackathon = response.Content.ReadAsAsync<Hackathon>().Result;
            // check if the selectedHackathon is null
            if (selectedHackathon == null)
            {
                // return to error action and give the error message
                return RedirectToAction("Error", new { message = "Unable to find the hackathon for editing" });
            }
            return View(selectedHackathon);
        }

        [HttpPost]
        public ActionResult Edit(Hackathon updatedHackathon)
        {
            string url = "hackathondata/edit/" + updatedHackathon.Id;
            string jsonpayload = jss.Serialize(updatedHackathon);
            Debug.WriteLine(jsonpayload);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // return to error action and give the error message
                return RedirectToAction("Error", new { message = "Unable to update the hackathon" });
            }

        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            //the existing hackathon information
            string endpoint = "hackathondata/findbyid/" + id;
            HttpResponseMessage response = client.GetAsync(endpoint).Result;
            Hackathon selectedHackathon = response.Content.ReadAsAsync<Hackathon>().Result;
            // add null checking for the selectedHackathon
            if (selectedHackathon == null)
            {
                // return to error action and give the error message
                return RedirectToAction("Error", new { message = "Unable to find the hackathon fo deletion" });
            }

            return View(selectedHackathon);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            string url = "hackathondata/delete/" + id;
            HttpResponseMessage response = client.DeleteAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // return to error action and give the error message
                return RedirectToAction("Error", new { message = "Unable to delete the hackathon" });
            }
        }

        // GET: Hackathon/Error
        public ActionResult Error(string message)
        {
            // using named parameter to pass the message to the view
            return View("Error", model: message);
        }
    }
}

HackathonTeamBuilder/Views/Hackathon/Create.cshtml
@model HackathonTeamBuilder.Models.Hackathon
@{
    ViewBag.Title = "Create Hackathon";
}

<div class="container mt-4">
    <h2>Create Hackathon</h2>

    @using (Html.BeginForm("Create", "Hackathon", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location)
            @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Location)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url)
            @Html.TextBoxFor(model => model.Url, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deadline)
            <input type="date" id="Deadline" name="Deadline" value=@DateTime.Now class="form-control"/>
            @Html.ValidationMessageFor(model => model.Deadline)
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    }
</div>

@section Scripts {
@*For form validation*@
    @Scripts.Render("~/bundles/jqueryval")
}

HackathonTeamBuilder/Views/Hackathon/DeleteConfirm.cshtml
@model HackathonTeamBuilder.Models.Hackathon
@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Delete Confirmation</h2>
<p class="text-danger">Are you sure you want to delete this hackathon?</p>
<p class="text-danger">Id: @Model.Id</p>
<p class="text-danger">Name: @Model.Name</p>
<a href="/hackathon/delete?id=@Model.Id" class="btn btn-danger">Confirm Delete</a>

HackathonTeamBuilder/Views/Hackathon/Detail.cshtml
@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

HackathonTeamBuilder/Views/Hackathon/Edit.cshtml
@model HackathonTeamBuilder.Models.Hackathon
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Hackathon</h2>

@using (Html.BeginForm("Edit", "Hackathon", FormMethod.Post, new { @class = "form-glass" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @Value = Model.Name })
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location)
        @Html.TextBoxFor(model => model.Location, new { @class = "form-control", @Value = Model.Location })
        @Html.ValidationMessageFor(model => model.Location)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description)
        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @Value = Model.Description })
        @Html.ValidationMessageFor(model => model.Description)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Url)
        @Html.TextBoxFor(model => model.Url, new { @class = "form-control", @Value = Model.Url })
        @Html.ValidationMessageFor(model => model.Url)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Deadline)
        <input type="date" id="Deadline" name="Deadline" value=@Model.Deadline.ToString("yyyy-MM-dd HH:mm") class="form-control" />
        @Html.ValidationMessageFor(model => model.Deadline)
    </div>

    <div class="form-group">
        <input type="submit" value="Save Changes" class="btn btn-primary mt-2" />
    </div>
}